#!/bin/bash
#mod_wsgi-express start-server wsgi.py --processes 4 --port 5000 --user adahal01 --group games --host=192.168.122.1


gunicorn -w 4 -b 0.0.0.0:8080 wsgi:app 2>> err.log

# NOTE: we may need worker nodes that are not "sync", look at them later
